"%prod":
  quarkus:
    datasource:
      username: fruits
      password: fruits
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import.sql