"%prod":
  quarkus:
    datasource:
      username: fruits
      password: fruits
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
    hibernate-orm:
      schema-management:
        strategy: drop-and-create
      sql-load-script: data.sql